### ISSUE TITLE
Train our own model

### ISSUE THREAD

**Issue by sailseem** [pth1993/DeepCE#1]
Dear developer,  

    This is a really great deep learning package for drug discovery. Well, I am wondering how can we train our own model? Or, you have trained well already by including all available L1000 data, so that we can just apply the model prediction for our own input? By the way, what's the input we could provide? Like drug list and gene expression profiles reflecting our interest? 

Thanks a lot.

**Comment by pth1993** [comment]
You can train the model on L1000 dataset to predict gene expression for new molecules. The training script and L1000 data are available at "script/train_deepce.sh" and "DeepCE/data" respectively.
